spring.application.name=gateway


server.port=8080

spring.cloud.gateway.server.webflux.routes[0].id=auth-service
spring.cloud.gateway.server.webflux.routes[0].uri=http://authentication-service:8081
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/auth/**

spring.cloud.gateway.server.webflux.routes[1].id=notes-service
spring.cloud.gateway.server.webflux.routes[1].uri=http://note-service:8082
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/note/**

logging.level.org.springframework.cloud.gateway=TRACE
logging.level.org.springframework.web=DEBUG

jwt.secret = "TmV3U2VjcmV0S2V5Rm9ySldUU2lnbmluZ1B1cnBvc2VzMTIzNDU2Nzg";